### ISSUE TITLE
Issue with 4.2.0.0 installer?

### ISSUE THREAD

**Issue by warmbaguettes** [stax76/mpv.net#27]
The new installer for 4.2 apparently fails to associate files at the end of the installation. I updated last night and at the end I chose Associate video files and after that the installer closes and leaves a mpv.net instance that stays idle and I have to kill via task manager. After that, I can open and associate files through mpv.net menu. 

Tried it a bunch of times and it does the same every time. Doesn't happen with 4.1 installer.

Using Windows 10 1903 x64 and x64 mpv.net installer.

**Comment by stax76** [comment]
It probably happened when I implemented the single process feature, I'll test it, thanks for reporting.

**Comment by stax76** [comment]
It was rather bad, so I've uploaded a new release, thanks again for investigating and reporting!

**Comment by warmbaguettes** [comment]
Hello again. Thanks for looking into the issue, however, unless you've uploaded the wrong binaries, the issue persists in the new version.

**Comment by stax76** [comment]
I just downloaded and decompiled it, it looks ok, it's very simple and I had tested it both by installing and by running it with debugger and both was fine.

**Comment by warmbaguettes** [comment]
Wish I could be more technical with my replies but I'm just an end-user. I just tried again and it does still happen but 4.1 works fine. If you think I can do something to help you better let me know.

**Comment by stax76** [comment]
I just tried with both 4.2 and 4.3 and couldn't reproduce it with either. I believe you because it makes sense looking at the code of 4.2 but in 4.3 the code is almost identical to prior 4.2 and it's very simple plus I tested it several times with and without debugger.

Some issues happen only sometimes or under very special circumstances, I suggest we leave this issue open in case more people experience it.

**Comment by warmbaguettes** [comment]
Sounds good, I can't think of anything else interfering with the installer in my system since it's basically a fresh Windows install. Besides, it works fine if I use the file association menu from mpv.net after installing.

**Comment by anonymous-user** [comment]
I have a similar issue. Using the file association feature adds mpv.net as a possible app for audio and video players but I still have to go into Windows 10 Settings and manually set mpv.net as the default. I tried with the association during installation and from the menu.

**Comment by stax76** [comment]
@anonymous-user 

In Win 7 it was possible to change the default app in the registry, Win 10 prevents this I believe, you have to change the default app in the settings or use the 'Open with' feature in Windows File Explorer. I don't think there is anything I can do.

**Comment by anonymous-user** [comment]
So it is working as intended then. Dang. Thanks.
