### ISSUE TITLE
The player has been broken after being moved to another display

### ISSUE THREAD

**Issue by dyphire** [stax76/mpv.net#449]
The display switching behavior has been severely broken since this commit: https://github.com/stax76/mpv.net/commit/34031fa15da25b895919e02539dd0f79ee7f80dc
**Expected behavior:** The player works normally after switching the display.
**Actual behavior:** The player can only resize the size of the window, other functions are invalid.

**Comment by stax76** [comment]
I tried switching with mouse and keyboard and with and without borders without finding an issue. My displays use the same resolution and same DPI.

**Comment by dyphire** [comment]
> I tried switching with mouse and keyboard and with and without borders without finding an issue. My displays use the same resolution and same DPI.

My displays use the same resolution, but different DPI.
The mouse control was broken after switching display, can only be used to adjust size; Keyboard control is normal.
The mouse controls work fine when tested with builds before to this commit: https://github.com/stax76/mpv.net/commit/34031fa15da25b895919e02539dd0f79ee7f80dc

**Comment by stax76** [comment]
Are borders enabled?

**Comment by stax76** [comment]
Unfortunately not reproducible.

Might it be related to your mpv config? Can be tried with `--config=no`.

**Comment by dyphire** [comment]
> Are borders enabled?

The result of enabling/disabling is the same.

> Can be tried with --config=no

It can be repetition by use mpvnet --no-config.

This is a screenshot:
![image](https://user-images.githubusercontent.com/61936050/175771331-f9e0b616-3ebe-4802-92a1-4ea0d13d8afc.png)
You can see that the mouse has a problem.

**Comment by dyphire** [comment]
I tried to adjust the displays to the same DPI for testing, but it still didn't work for me. 
Same mouse problem. This confuses me.

**Comment by stax76** [comment]
As the commit message states, it's the code that allows to resize a borderless window. That code is always in use even if borders are enabled. It's probably possible to disable the code if borders are active, I will try this.

**Comment by dyphire** [comment]
> As the commit message states, it's the code that allows to resize a borderless window. That code is always in use even if borders are enabled. It's probably possible to disable the code if borders are active, I will try this.

I tried to remove these code from the latest code for build tests, and the test results showed that the player worked normally. So I can confirm that this commit caused the problem.

**Comment by stax76** [comment]
I committed what I believe will fix it when borders are active, please try now both, with borders and without borders, without borders might still not work, and it might be very difficult to find the reason since I cannot reproduce it.

**Comment by stax76** [comment]
What GPU brand are you using? NVIDIA here.

**Comment by dyphire** [comment]
> I committed what I believe will fix it when borders are active, please try now both, with borders and without borders, without borders might still not work, and it might be very difficult to find the reason since I cannot reproduce it.

The latest commit fixes the mouse control when the border is open, but it still doesn't work when there is no border.
As a temporary solution I kept removing these code in fork.

**Comment by dyphire** [comment]
> What GPU brand are you using? NVIDIA here.

smae NVIDIA, GTX 1060

**Comment by stax76** [comment]
OK, please try if mpv without borders creates the problem. I copied the code somewhere from GitHub, it's not exactly the same code as used by mpv uses, but likely very similar.

**Comment by dyphire** [comment]
> OK, please try if mpv without borders creates the problem. I copied the code somewhere from GitHub, it's not exactly the same code as used by mpv uses, but likely very similar.

From the beginning, I've done some comparison tests with mpv, and it still works with  no-border. Sorry I didn't mention that in the first place.

**Comment by stax76** [comment]
OK, thanks for testing, I will review the code.

**Comment by stax76** [comment]
It's likely fixed with the last commit.

**Comment by dyphire** [comment]
> Please try if the last commit fixes it.

I tested the build based on the latest commit, but unfortunately the problem was not resolved. Same results as before.

Can you reopen this issue?

**Comment by stax76** [comment]
Thanks for testing. I have no idea why it's not reproducible, I use Windows 11 too.

**Comment by stax76** [comment]
I found out now how to reproduce it:

Changing the setting 'Make this my main display'

**Comment by stax76** [comment]
Should finally be fixed!

**Comment by dyphire** [comment]
> Should finally be fixed!

Now it is perfect.
